### ISSUE TITLE
Unable to install latest fix for HMC, aka MF71299

### ISSUE THREAD

**Issue by christophegehin** [IBM/ansible-power-hmc#113]
**Describe the bug**
Unable to install latest fix for HMC, aka MF71299

**To Reproduce**
Execute that playbook :
- hosts: all
  connection: local
  gather_facts: false

  tasks:

  - name: update hmc
    ibm.power_hmc.hmc_update_upgrade:
      hmc_host: "{{ inventory_hostname }}"
      hmc_auth:
        username: XXXXXXXXX
        password: XXXXXXXXX
      build_config:
        location_type: disk
        build_file: /ansible/dev/rpzbg569/hmc/MF71299
      state: updated
    register: results

Error :
TASK [update hmc] ***************************************************************************************************************************************************************************************************************************
fatal: [labhmc342]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Error: copy of image to hmc is incomplete. Necessary files are missing"}

**Expected behavior**
Fix should be installed successfully
FYI, with previous fix, aka MF71191, I was able to install it without any error.

**Screenshots**

**Environment (please complete the following information):**
- HMC: V2R10M1041
- Python Version : 3.6.8
- OpenSSH Version :openssh-8.0p1-19.el8_8.x86_64

**Additional context**
I had a quick look in the code of the module hmc_update_upgrade. After the copy of all files in the folder, it launches a "ls" command to check if all files have been copied.
Then it checks in the output if the first file is an ISO file.

For MF71299, the first file is not an ISO file, and so, the module is failing=>
ls -l
total 2003276
-rw-rw-r--. 1 rpzbg569 rpzbg569       3980 Oct 11 08:08 vMF71299.dd.xml
-rw-rw-r--. 1 rpzbg569 rpzbg569       2531 Oct 11 08:08 vMF71299.pd.sdd
-rw-rw-r--. 1 rpzbg569 rpzbg569 2051323904 Oct 11 08:14 vMF71299_ppc.iso
-rw-rw-r--. 1 rpzbg569 rpzbg569      10460 Oct 11 08:08 vMF71299.readme.html
-rw-rw-r--. 1 rpzbg569 rpzbg569       5335 Oct 11 08:08 vMF71299.txt

For MF71191, the first file is an ISO file, and the module is not failing =>
ls -al
total 9845424
-rw-r--r-x    1 rpzbg569 suadm    5040805888 Aug 30 07:09 HMC_Update_V10R2M1041_ppc.iso
-rw-r--r-x    1 rpzbg569 suadm          4435 Aug 30 07:09 MF71191.dd.xml
-rw-r--r-x    1 rpzbg569 suadm          2861 Aug 30 07:09 MF71191.pd.sdd
-rw-r--r-x    1 rpzbg569 suadm         16150 Aug 30 07:09 MF71191.readme.html
-rw-r--r-x    1 rpzbg569 suadm          9855 Aug 30 07:09 MF71191.txt

Could you please fix that module ?

Thanks you

**Comment by neikei** [comment]
Can you try to specify the path of the iso completely?

```yaml
# Example
build_file: /ansible/dev/rpzbg569/hmc/MF71299/vMF71299_ppc.iso
```

There are a few "list_cmd" file listings via "ls" which look like they produce this situation.

https://github.com/IBM/ansible-power-hmc/blob/de4f3bf98b9643cbaecc6d4998caa851c4c92ade/plugins/modules/hmc_update_upgrade.py#L386

**Comment by christophegehin** [comment]
I tried with iso file as suggested and got an error :

fatal: [labhmc342]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Error: copy of image to hmc failed"}

**Comment by opokam** [comment]
Did IBM remove the /usr/bin/python from the HMC?  I see a /usr/bin/python3. Also, in the name of hardening, IBM is removing, in the targeted fix, all options to sed.  This seems to break iconic scripts like ezh/eezh.  I'm not sure if any of the ansible modules call sed from the HMC.

**Comment by christophegehin** [comment]
I'm using an inventory file with ansible_connection=local for each HMC.
So the python is executed on my ansible controler and not on the HMC.

Regards
