### ISSUE TITLE
Missing poolID parameter with modules ibm.power_hmc.powervm_lpar_migration

### ISSUE THREAD

**Issue by claudeparadis** [IBM/ansible-power-hmc#115]
In module powervm_lpar_migration, parameters for poolID, both processror and memory, are missing.

This causes the migrating partition to always end up in the DefaultPool.

A workaround is to get the source poolID before the migration and move the partition to it after the migration.

**Comment by kmkamyk** [comment]
I'm bumping it up!
The ability to select a processor pool would be a big improvement for this module.

**Comment by naveenkandakur** [comment]
Taken care as of August-2024 release content, hence closing this.
