### ISSUE TITLE
powervm_lpar_instance incorrectly requires proc_unit to be a multiple of the minimum proc unit per vp (0.05 fince Power7+)

### ISSUE THREAD

**Issue by dferrand** [IBM/ansible-power-hmc#119]
**Describe the bug**
When using powervm_lpar_instance to create or modify an LPAR instance, the module requires the proc_unit to be a multiple of the minimum proc unit per vp (which is 0.05 since Power7+). PowerVM doesn't have such a requirement.

**To Reproduce**
1. use powervm_lpar_instance to create a LPAR instance and specify a proc_unit value of 0.08 (for example).

**Expected behavior**
There shouldn't be an error.

**Environment (please complete the following information):**
 - HMC: 10.2.1030
 - Python Version 3.10.12
 - OpenSSH Version 1.7.5

**Comment by naveenkandakur** [comment]
We are not setting the minimum proc unit per vp value to be multiple of 0.05 explicitly, we rely on the value of Managed System's "MinimumProcessorUnitsPerVirtualProcessor" parameter and expects multiple of that value.
So marking this as Working as designed.

**Comment by dferrand** [comment]
> We are not setting the minimum proc unit per vp value to be multiple of 0.05 explicitly, we rely on the value of Managed System's "MinimumProcessorUnitsPerVirtualProcessor" parameter and expects multiple of that value. So marking this as Working as designed.

That's exactly the behavior I described, the issue is that this control doesn't make sense, PowerVM doesn't have such a requirement, you should be able to create a LPAR instance with a proc_unit value of 0.08, which is currently impossible with powervm_lpar_instance

**Comment by naveenkandakur** [comment]
We are using HMC's RestAPI's to create LPAR and HMC doesn't support it, so we can't support.
