### ISSUE TITLE
hmc_update_upgrade disk pathing isn't correct

### ISSUE THREAD

**Issue by BladesOfSteele** [IBM/ansible-power-hmc#125]
The path for where the updhmc command is using, doesn't match what's passed to the module.

I copied the iso to /home/padmin and ran the upgrade module
    - name: Update the HMC to ?
      hmc_update_upgrade:
        hmc_host: '{{ hmc_hostname }}'
        hmc_auth:
          username: '{{ ansible_user }}'
          password: '{{ ansible_password }}'
        build_config:
          location_type: disk
          build_file: /home/padmin/HMC_Update_V10R3M1051_ppc.iso
        state: updated

When running with the -vvv flag, see the following:
Apr 12 20:27:32 localhost HMC[27466]: HSCE2124 User name hscroot: updhmc -t disk -f /home/padmin/HMC_Update_V10R3M1051_ppc.iso/home/padmin/HMC_Update_V10R3M1051_ppc.iso -r command failed.

**Comment by BladesOfSteele** [comment]
In looking at this closer and reviewing the code. When using the location type disk, it's looking for a directory, not an ISO file, then copies all the files from the directory to the HMC. Not sure I follow that logic. One would have to be prudent to have only a single iso per directory.

**Comment by naveenkandakur** [comment]
Yes, we have to mention the directory path containing ISO file incase of update and  path until network_install directory in case of upgrade, Please refer the documentation - https://ibm.github.io/ansible-power-hmc/modules/hmc_update_upgrade.html
Let me know if you need any other details.

**Comment by naveenkandakur** [comment]
Now we are supporting iso file as well as directory
Taken care as of August-2024 release content, hence closing this.
