### ISSUE TITLE
[ Bug / Feature ] Improve idempotency of modules

### ISSUE THREAD

**Issue by justin-davisibm** [IBM/ansible-power-hmc#128]
**Describe the bug**
A number of the modules within the HMC collection are not idempotent, requiring additional checks around them for functionality.

Ideally, running a module should describe the system's desired state, not it's current one (see https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html#desired-state-and-idempotency). 

To compound this, the errors raised need to be processed via textual checks, which is poor practice.

**To Reproduce**
Currently I have found the following examples:
- Creating a new LPAR with the same name as an existing LPAR
- Attempting to get-info of an LPAR that does not exist (returns error instead of information).
- Attempting to delete a non-existant LPAR raises an error
- Attempting to Power on an already Powered on LPAR raises an error
- Attempting to Power off an already Powered off LPAR raises an error
- Deleting a powered on LPAR raises an error.

**Expected behavior**
Ideally in the cases above:

- Creating a new LPAR with the same name as an existing LPAR
    - The LPAR is already created, the play should complete with no changes made
- Attempting to get-info of an LPAR that does not exist (returns error instead of information).
    - The module should not error, and return a "LPAR not found" or similar message in it's success notification
- Attempting to delete a non-existant LPAR raises an error
    - The resource does not exist, therefore the deletion as requested has completed. This play should complete with an unchanged state, not an error.
- Attempting to Power on an already Powered on LPAR raises an error
   - The resource is already in desired state, similar to deletion above, play should complete with an unchanged state.
- Attempting to Power off an already Powered off LPAR raises an error
   - The resource is already in desired state, similar to deletion above, play should complete with an unchanged state.
- Deleting a powered on LPAR raises an error.
   - A deletion should not require an additional state change. If I request a deletion, I should not need to also process a power down action.

**Screenshots**

**Environment (please complete the following information):**
 - HMC: V10.3.1050
 - Python Version  3.9.18-3.el9 
 - OpenSSH Version  8.7p1-38.el9 

**Additional context**

**Comment by AnilVijayan** [comment]
We are working on it, will be delivered with Aug Release

**Comment by naveenkandakur** [comment]
Taken care as of August-2024 release content, hence closing this.
