### ISSUE TITLE
Partition Mobility support please!!!

### ISSUE THREAD

**Issue by netamego** [IBM/ansible-power-hmc#14]
Hi!!

I think it is a very good and necessary initiative. Seems that is in very early stage... lots of encouragement!!!!. I dream of being able to run partition mobility tasks and include it in our automated ansible workflow validation for our disaster recovery plan.

Best regards.

**Comment by AnilVijayan** [comment]
Thanks for showing interest in Ansible modules for HMC and letting us know your requirement. We will evaluate adding LPM support as part of our plan/roadmap

**Comment by chico35400** [comment]
hello folks,

thanks to all for the great job done so far!
and as netamego i dream to ansible my partion management (power on,power off,ect...) for automated disaster recovery plan or maintenance scripts.

Good job and happy new year!

**Comment by AnilVijayan** [comment]
Delivered the feature with PR #55
