### ISSUE TITLE
Please allow physical I/O slot assignments when creating LPAR

### ISSUE THREAD

**Issue by stephenulmer** [IBM/ansible-power-hmc#24]
**Is your feature request related to a problem? Please describe.**
`powervm_lpar_instance` is *so* very close to being what I need.

**Describe the solution you'd like**
It would be *extremely* helpful if the module would allow assigning I/O slots when defining a partition. It would be great if they could be specified with full or partial (but unique) location codes. For example, if there is only one drawer in the system, we could avoid specifying the part of the location before the first '-', which identifies the drawer by serial.

Please do the DRC_index lookups in the module, as most mortals don't use them regularly.

If I still have to do the lookups for the first part of the DRC_slot_name it would still be *much* better than having to assign the slot myself later.

**Describe alternatives you've considered**
I am currently interacting with the HMC via the **raw** module, doing the text processing necessary to convert locations to DRC_index values with Jinja2, and then updating the partition profile to contain only the slots I need with **raw** again. This is a ball of ugly: more than half of the playbook is is dealing with slot assignments, and the Ansible facilities available for error checking with **raw** are less than elegant.

**Comment by AnilVijayan** [comment]
Added this feature with #36 
Document reference [https://ibm.github.io/ansible-power-hmc/modules/powervm_lpar_instance.html#parameters](url)
