### ISSUE TITLE
Question: Processor compatibility mode on a lpar definition

### ISSUE THREAD

**Issue by metabsd** [IBM/ansible-power-hmc#25]
Can I use the lpar module to change the default profile of an lpar? For example when updating an AIX server I would like to change the Processor compatibility mode and make sure it is at POWER8. Thank you very much for your contribution to Ansible :)

**Comment by hari-g-m** [comment]
Hi, 
   Currently, changing default profile of an lpar is not supported via the lpar module. We can look at it as an enhancement. However , had a question on the requirement - Is your requirement to change the proc compat mode from default to a specific value ? If proc compat mode is provided as an input when creating the partition, would it address the requirement? 

Thanks.

**Comment by AnilVijayan** [comment]
Added this feature with PR #69
