### ISSUE TITLE
Missing meta/runtime.yml

### ISSUE THREAD

**Issue by thedoubl3j** [IBM/ansible-power-hmc#30]
**Describe the bug**
this collection is missing a meta/runtime.yml file which will be used by Automation Hub/ansible to determine which version(s) of ansible this collection supports. 
**To Reproduce**
navigate to top level of collection, no meta directory found.
**Expected behavior**

runtime.yml file present for housing versions of ansible supported

**Screenshots**
ex: ```requires_ansible: ">=2.9,<2.11"```

**Environment (please complete the following information):**
n/a

**Additional context**
docs for meta directory https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#meta-directory

**Comment by AnilVijayan** [comment]
Thanks for pointing out. Will push the suggested file

**Comment by AnilVijayan** [comment]
Closing as this is handled now
