### ISSUE TITLE
Incorrect check for available core count in powervm_lpar_instance 

### ISSUE THREAD

**Issue by cunlifs** [IBM/ansible-power-hmc#32]
Hi, when using powervm_lpar_instance modules to build a new LPAR profile, the proc_units value is incorrectly checked.

For example on a frame with 1.4 cores available and proc_units: 0.5 and proc: 2 requested in the module, it fails saying please select 1 or less for proc value. If you lower to 1 virtual proc it works.

**Comment by AnilVijayan** [comment]
Fixed with #36
