### ISSUE TITLE
Pass ad-hoc HMC commands via SSH

### ISSUE THREAD

**Issue by bricevollmer** [IBM/ansible-power-hmc#35]
I'd like to pass HMC commands via SSH through ansible out to multiple HMCs. Can we have a module/plugin created for hmc_cli

Example:
Run 'chsacfg -t custinfo -o set' to update customer information

**Comment by AnilVijayan** [comment]
Thanks for showing interest, will consider it in our pipeline

**Comment by AnilVijayan** [comment]
Delivered the feature with PR #55
