### ISSUE TITLE
Can you provide NPIV details as facts?

### ISSUE THREAD

**Issue by NicolaeCh** [IBM/ansible-power-hmc#40]
It will be very useful to retrieve WWPN  of NPIV as facts - for the new created LPAR it will facilitate the provisioning. The WWPN can be then used to generate the host in the storage system and the zones in FC switch. It will result in a full automation of provisioning process.

**Comment by AnilVijayan** [comment]
Will evaluate it to accommodate on next release

**Comment by Rony-Flores** [comment]
Hi, I found this useful for an inner project, currently using this for zones in FC switch of storage, I just did a pull request https://github.com/IBM/ansible-power-hmc/pull/50 to add this details into stdout for parameter **state** with value **_present_** and **_facts_**, it would be this nice to have on next release.

**Comment by AnilVijayan** [comment]
Delivered the feature with PR #55
