### ISSUE TITLE
Manage HMC users and their SSH-keys via Ansible module

### ISSUE THREAD

**Issue by neikei** [IBM/ansible-power-hmc#41]
**Is your feature request related to a problem? Please describe.**
As an admin I have to create, update and delete users on the HMC and manage their SSH-keys. 

**Describe the solution you'd like**
Add an Ansible module to manage users and their keys.

**Describe alternatives you've considered**
Use the shell module and the following commands to manage users and keys, but this is not preferred.

- chhmcusr
- lshmcusr
- mkhmcusr
- rmhmcusr
- mkauthkeys

**Additional context**
None

**Comment by AnilVijayan** [comment]
Will add this into our roadmap

**Comment by AnilVijayan** [comment]
Added user management support with #78
