### ISSUE TITLE
Max/min support for proc en memory

### ISSUE THREAD

**Issue by tpeponas** [IBM/ansible-power-hmc#42]
Hello,

Could you add parameter for min/max proc unit and memory to module powervm_lpar_instance
for example : 
proc: 1
proc_unit: 0.5
mem: 2048
min_mem: 1024
max_mem: 8196
min_proc: 1
max_proc: 4
min_proc_unit: 0.1
max_proc_unit: 2.0

Regards

**Comment by AnilVijayan** [comment]
Will consider this as  part of our April content

**Comment by simplyunix** [comment]
Hi there, please can you advise if this feature has been added.
Kind Regards
Sasi

**Comment by AnilVijayan** [comment]
Yes this feature will be available with April content

**Comment by ALutz273** [comment]
@AnilVijayan Thanks in version 1.5 it is available. I think the issue can be closed.

**Comment by AnilVijayan** [comment]
As this feature is delivered closing this issue
