### ISSUE TITLE
power_hmc.powervm_lpar_instance may assign a physical_io location that is a superstring of the requested one

### ISSUE THREAD

**Issue by stephenulmer** [IBM/ansible-power-hmc#46]
**Describe the bug**
Adding the following list as the parameter for physical_io:
          - P1-C12
          - P1-C4
          - P1-C3
          - P1-C9
          - P1-T4

Results in these "slots" being added to the LPAR:
          - P1-C12
          - P1-C49
          - P1-C3
          - P1-C9
          - P1-T4

FWIW, C4 is the FC HBA I want to use, and C49 is an internal disk controller (with no attached drives). This is probably just a broken match that isn't anchored at the end of the comparison properly.

**Additional context**
The managed system is a Power S922 (A-model). A different model of system may not have any locations that are a proper substring of another one.

**Comment by AnilVijayan** [comment]
Yes the issue is related to matching of similar location code. Will push a PR soon, and currently targeting to upstream to galaxy and hub along with December release
