### ISSUE TITLE
ibm.power_hmc.powervm_lpar_instance module: Allow Virtual Fibre slot numbers to be specified

### ISSUE THREAD

**Issue by Rich-J-AIX** [IBM/ansible-power-hmc#49]
**ibm.power_hmc.powervm_lpar_instance module: Allow Virtual Fibre slot numbers to be specified**
When creating virtual Fibre adapters for NPIV, the powervm_lpar_instance module uses the next available slots.
A client has requested that they would like to specify the slot numbers to conform with their existing standards.

**Desired solution**

1. Allow selection of virtual fibre client adapter slot numbers to a given value.
2. Allow selection of virtual fibre server adapter slot number to either 
   a) a given value
   or
   b) the next available number after a starting value.

Client standard procedure dictates that the server slots created would be in a sequential block from a given starting value.
Such that if 3 adapters are requested per VIOS, then the next available block of 3 consecutive numbers would be used after the starting value.

**Workaround**

Currently the client has created additional virtual fibre adapters with the module to ensure the client slot numbers match their standards, and then created a playbook to remove the unwanted adapters. 
Whilst the client slot numbering can conform to their standards with this method, the server slot numbers are in the wrong range and could interfere with their numbering convention for virtual network adapters.

As the selection of a free consecuative block may be tricky to engineer, providing a given slot number is probably a simpler solution.

**Comment by AnilVijayan** [comment]
Will consider this as part of our April content

**Comment by simplyunix** [comment]
Hello there.

Please can you advise if this feature has been added.

Kind regards
Sasi

**Comment by AnilVijayan** [comment]
Added this feature with PR #69
