### ISSUE TITLE
Power an lpar with network boot

### ISSUE THREAD

**Issue by sdelabarre** [IBM/ansible-power-hmc#54]
Hello,
It would be very useful if we could the bootlist of an LPAR/VM before powering it on, with something similar to :

`chsyscfg -r lpar -m {{ powervm }} -i "name={{ lparname }},boot_string=\"{{network[0].of_path_name | default ('/vdevice/l-lan@3000000c')}}:speed=auto,duplex=auto,bootp,{{kickstart_server.ip}},,{{ network[0].ip }},{{ network[0].gateway }}\""`

Or, may be allow lpar_netboot :

`lpar_netboot -f -T off -t ent -s auto -d auto -m mac_address -S serverIP -G gw_IP -C clientIP lpar_name profile  mnged_node `

**Comment by AnilVijayan** [comment]
Will consider this as part of our AIX OS installation support which is there in our pipeline

**Comment by sdelabarre** [comment]
This is also valid for Linux Kickstart installation. Txs @AnilVijayan .

**Comment by AnilVijayan** [comment]
Added the lpar netboot based install support of AIX and Linux with PR #78
