### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by robinsg** [IBM/ansible-power-hmc#61]
I've downloaded and install the 1.4.0 collection to try some of the new features.

When I try and run a playbook using the hmc_command module I get a message back saying:

FAILED! => {"changed": false, "msg": "HmcError: Host public key is unknown. sshpass exits without confirming the new key."}

If I attempt to ssh in to the HMC using password or RSA key it works fine.

Any suggestions on how to fix this?

Thanks
Glenn

**Comment by AnilVijayan** [comment]
The ansible control node (node in which ansible engine present) should accept the known host keys of all the HMCs. Generally it is stored on ~/.ssh/known_hosts. Please check if the known_hosts file inside control node containing the connecting HMC

**Comment by AnilVijayan** [comment]
Added the support to ignore host key checking with env `ANSIBLE_HOST_KEY_CHECKING`. 
User can set this env as `false` to ignore the checking.
