### ISSUE TITLE
IBM HMC groups 

### ISSUE THREAD

**Issue by mhs1027** [IBM/ansible-power-hmc#63]
I have created group in IBM HMC i.e group for PROD servers, group for DR servers and a group for UAT servers.
UAT and PROD servers are in same frames but I want to differentiate that in dynamic inventory. How can I pull/import/filter/group those groups from IBM HMC to dynamic inventory file.
I have tried to define that like other filters: PartitionState or PartitionType but that did not work as it is not pulling/reading from my IBM HMC. I have tried defining like other groups AIX_72 or AIX_71 but that did not help either.
Is this feature already exists ? if it does how can I use that

**Comment by AnilVijayan** [comment]
I assume you wanted to group a set of power servers into different usage groups like 'PROD', 'DR' and 'UAT'. This is currently not supported by the dynamic inventory plugin, instead as of today it can only group the partitions part of a server.
We can consider this as a enhancement request if that is the one you are looking for.

**Comment by mhs1027** [comment]
Anil,
Yes I am looking for that enhancement so I can categorize and create my dynamic inventory based on environment. Currently I am using server name and creating manual groups to differentiate between environments. But If i can pull group information from HMC directly, it will make things a lot easier.

Thanks
Mohsin.
