### ISSUE TITLE
inventory settings - python interpreter

### ISSUE THREAD

**Issue by bricevollmer** [IBM/ansible-power-hmc#64]
Do we need to specify a python interpreter version or any other parameters in the inventory hosts file? I am receiving the following error when executing a playbook using the hmc_command module:

TASK [Update customer information ] ***************************************************************************************************************************************
fatal: [server]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "HmcError: /bin/sh: -c: line 0: syntax error near unexpected token `)'/bin/sh: -c: line 0: `sshpass -p  ******** ssh ********@server 'chsacfg -t custinfo -o set -i \"admin_company_name=company,admin_name=name,admin_email=email,admin_phone=number,admin_addr=address,admin_city=,admin_country=US,admin_state=state,admin_postal_code=zip,sys_use_admin_info=1\"''"}

**Comment by AnilVijayan** [comment]
hmc_command module uses /bin/sh as its shell. Could you please confirm if you are able to run any script in your control node using '/bin/sh' . Also can you try the build-in _shell_ module of ansible to execute some generic linux command to confirm that it is not leading to any error. For example as below,
```
- tasks:
  name: Test shell
  shell: uname -a
```
