### ISSUE TITLE
ibm.power_hmc.powervm_lpar_instance module - LPAR IDs and vFC client/server adapter slot numbers

### ISSUE THREAD

**Issue by simplyunix** [IBM/ansible-power-hmc#65]
Hello
1. Can we specify the **LPAR ID** when deploying virtual machines? 
2. Can we specify **vFC client/server adapter slot numbers**?

I had look but could not find a option. Please can you let me if this feature is available in this module

Kind Regards
Sasi

**Comment by AnilVijayan** [comment]
Hi,
1. Currently we don't let the user to specify LPAR ID, instead it will be auto assigned. If you have any significant use case for this, we can think of it.
2. Yes this feature will be supported with our next content which will be released by the end of this April

**Comment by simplyunix** [comment]
Thanks Anil for a quick response.
1. I have come across clients using LPAR id to customize the vFC slot numbers
Also on the GUI/CLI we can current choose so it will make sense to have this included in the module

Just a thought :-)
Kind Regards
Sasi

**Comment by AnilVijayan** [comment]
Added the support for configuring slot num for vFC client and server with PR #69 
Will add the lpar ID support with next release.

**Comment by AnilVijayan** [comment]
Added the lpar id config support with PR #78
