### ISSUE TITLE
ibm.power_hmc.powervm_lpar_instance module - Shared Processor Pool 

### ISSUE THREAD

**Issue by simplyunix** [IBM/ansible-power-hmc#66]
Hi there.
Shared Processor Pool  is important attribute from licensing point of view for IBMi LPARS
Please can you let me know if this feature is currently available in this module? At a glance I could not see anything related to it.

This will be good to have if it can also be included in the next content release

Kind Regards
Sasi

**Comment by AnilVijayan** [comment]
Added this feature with PR #69
