### ISSUE TITLE
NPIV can't be read on fact

### ISSUE THREAD

**Issue by gdelbrusco** [IBM/ansible-power-hmc#67]
Hello this is an role for read fact of lpar that already exist but no NPIV information we be displayed 

```
- name: "loop on lpar inventory"
  collections:
    - ibm.power_hmc
  powervm_lpar_instance:
    hmc_host: '{{ inventory_hostname }}'
    hmc_auth:
      username: '{{hmc_user}}'
      password: '{{hmc_pass}}'
    system_name: '{{item.frame}}'
    vm_name: '{{item.name}}'
    state: facts
    advanced_info: true
  register: powervm_lpar_instances
  loop: '{{lpar}}'

- name: Debug
  debug:
    var: powervm_lpar_instances

```

the output display this info 
ok: [x.x.x.x] => (item={'name': 'tusdpsxs01v', 'frame': 'Server-9040-MR9-SNXXXXXXX', 'virtualcpu': 2, 'physicalcpu': 0.6, 'memory': 10240, 'netname': 'VLAN1167', 'virtual_switch': 'ETHERNET0', 'virtual_slot': 5, 'netname1': 'VLAN1166', 'virtual_slot1': 6, 'netname2': 'VLAN1168', 'virtual_slot2': 7, 'viosname': 'shvsdpvio1b', 'fcport': 'fcs0', 'fcport1': 'fcs1', 'viosname1': 'shvsdpvio2b', 'fcport2': 'fcs2', 'fcport3': 'fcs3', 'max_virtual_slots': 200, 'os_type': 'aix'})

no WWN displayed

**Comment by AnilVijayan** [comment]
Upcoming April release going to have this feature

**Comment by AnilVijayan** [comment]
Added this feature with PR #69
