### ISSUE TITLE
Create Lpar with vNIC network adapter

### ISSUE THREAD

**Issue by ALutz273** [IBM/ansible-power-hmc#74]
**Is your feature request related to a problem? Please describe.**
Hello the new method to deploy lpars is vNIC. 

**Describe the solution you'd like**
I would like to have a vNIC Lpar with multiple backing adapters.

**Describe alternatives you've considered**

**Additional context**
![grafik](https://user-images.githubusercontent.com/72616997/166880693-8eee4b41-c6c6-4660-938e-b7269dd21992.png)

**Comment by AnilVijayan** [comment]
Will add this in our roadmap

**Comment by ALutz273** [comment]
Thank you. When is it planned to release a new realase?

**Comment by AnilVijayan** [comment]
Added the support with PR #78
