### ISSUE TITLE
Unable to run hmc_command in restricted hscroot shell

### ISSUE THREAD

**Issue by rellies** [IBM/ansible-power-hmc#75]
**Describe the bug**
Ansible returns unavailable with msg:

msg: 'Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in "/tmp", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p "` echo ~./ansible/tmp `"&& mkdir "` echo ~./ansible/tmp/ansible-tmp-1652984846.243839-82432-233859373566647 `" && echo ansible-tmp-1652984846.243839-82432-233859373566647="` echo ~./ansible/tmp/ansible-tmp-1652984846.243839-82432-233859373566647 `" ), exited with result 127'

Upon `-vvv` error observation, the error seems to point to not being able to run `sh -c`, due to sh not existing in /hmcrbin or /usr/hmcrbin. Symlinking corrects this issue, but will be overridden on the next HMC update.

-vvv output:
```shell
<hmc11> ESTABLISH SSH CONNECTION FOR USER: hscroot
<hmc11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="hscroot"' -o ConnectTimeout=10 -o 'ControlPath=~/.ansible/tmp/ansible-ssh-%h-%p-%r' hmc11 '/bin/sh -c '"'"'echo ~. && sleep 0'"'"''
<hmc11> (1, b'', b"/bin/bash: /bin/sh: restricted: cannot specify `/' in command names\n")
<hmc11> Failed to connect to the host via ssh: /bin/bash: /bin/sh: restricted: cannot specify `/' in command names
<hmc11> ESTABLISH SSH CONNECTION FOR USER: hscroot
<hmc11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="hscroot"' -o ConnectTimeout=10 -o 'ControlPath=~/.ansible/tmp/ansible-ssh-%h-%p-%r' hmc11 '/bin/sh -c '"'"'echo "`pwd`" && sleep 0'"'"''
<hmc11> (1, b'', b"/bin/bash: /bin/sh: restricted: cannot specify `/' in command names\n")
<hmc11> Failed to connect to the host via ssh: /bin/bash: /bin/sh: restricted: cannot specify `/' in command names
<hmc11> ESTABLISH SSH CONNECTION FOR USER: hscroot
<hmc11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="hscroot"' -o ConnectTimeout=10 -o 'ControlPath=~/.ansible/tmp/ansible-ssh-%h-%p-%r' hmc11 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~./ansible/tmp `"&& mkdir "` echo ~./ansible/tmp/ansible-tmp-1652978341.5662153-14090-51854304798782 `" && echo ansible-tmp-1652978341.5662153-14090-51854304798782="` echo ~./ansible/tmp/ansible-tmp-1652978341.5662153-14090-51854304798782 `" ) && sleep 0'"'"''
<hmc11> (1, b'', b"/bin/bash: /bin/sh: restricted: cannot specify `/' in command names\n")
<hmc11> Failed to connect to the host via ssh: /bin/bash: /bin/sh: restricted: cannot specify `/' in command names
fatal: [hmc11]: UNREACHABLE! => changed=false 
  msg: 'Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in "/tmp", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p "` echo ~./ansible/tmp `"&& mkdir "` echo ~./ansible/tmp/ansible-tmp-1652978341.5662153-14090-51854304798782 `" && echo ansible-tmp-1652978341.5662153-14090-51854304798782="` echo ~./ansible/tmp/ansible-tmp-1652978341.5662153-14090-51854304798782 `" ), exited with result 1'
  unreachable: true
```

**To Reproduce**
Command run: 
```shell 
ansible-playbook -vvv -i hosts-hmc hmc-command-tst.yml -l hmc11
```

Playbook:

```yaml
- name: Ansible playbook for testing hmc_command
  hosts: hosts-hmc
  order: sorted
  gather_facts: no
  connection: local
  tasks:
     - name: SSH To HMC and run uname
       ibm.power_hmc.hmc_command:
         hmc_host: '{{inventory_hostname}}'
         hmc_auth: 
            username: '{{ansible_user}}'
         cmd: uname -a
```

**Expected behavior**
normal stdout

**Environment (please complete the following information):**
 - HMC: 
hscroot@hmc11:~> lshmc -V
"version= Version: 10
 Release: 1
 Service Pack: 1011
HMC Build level 2202161537
MF69180 - HMC V10R1 M1011
MF69262 - iFix for HMC V10R1 M1011
MF69288 - iFix for HMC V10R1 M1011
","base_version=V10R1
"

 - Python Version 
 `[root@hmc11] # python3 -V      
Python 3.6.8`

 - OpenSSH Version
`hscroot@hmc11:~> ssh -V
OpenSSH_8.0p1, OpenSSL 1.1.1g FIPS  21 Apr 2020`

**Additional context**
Not sure if the platform-python will execute successfully either.

**Comment by AnilVijayan** [comment]
This issue looks like, not using the `connection: local` option which is mandated in case of HMC collections.Refer [https://ibm.github.io/ansible-power-hmc/quickstart.html#connection-method](url).
I do agree the local connection setting only used on the playbook you have shared, but the execution result doesn't indicate that. If the connection was local the debug message would have contained below message
`ESTABLISH LOCAL CONNECTION FOR USER: root`
Instead it is showing,
`ESTABLISH SSH CONNECTION FOR USER: hscroot`
That means for some reason the ansible engine trying to execute the binary on the remote HMC instead of local host machine(control node).

**Comment by rellies** [comment]
I had an `ansible_connection=ssh` variable that I missed in my `hosts-hmc` , so I believe Ansible was defaulting to ssh no matter what connection I was setting in the Playbook. After changing and rerunning the playbook, I get expected results:

```Shell
changed: [hmc11] => changed=true 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  command_output:
  - 'Linux hmc11 4.18.0-305.19.1.el8.hmc9_0p.7.x86_64 #1 SMP Tue Oct 26 00:13:36 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux'
  invocation:
    module_args:
      cmd: uname -a
      hmc_auth:
        password: null
        username: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      hmc_host: hmc11
```

I believe that's probably intended by Ansible Engine, so I'm not sure if any change is needed.

**Comment by mshakeer03** [comment]
I have a situation where, in between the Ansible controller (I am using Ansible Tower) and the HMC there is a jumphost or proxy through which all the connections to the endpoints are made, in here how can I make use of the connection=local so that I get these modules working. Perhaps I will try with delegate_to proxy in my playbooks.

**Comment by mshakeer03** [comment]
The delegate_to option doesn't work either, the connection to the HMC gets timed out, from the ansible tower through the proxy I am able to run HMC commands using the raw module, but when using the POWER HMC modules it doesn't connect, the connection path is same in either case, 

<jumphost_IP> ESTABLISH LOCAL CONNECTION FOR USER: awx
<jumphost_IP> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<jumphost_IP> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp `"&& mkdir "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1690536487.1952565-22-102426177066420 `" && echo ansible-tmp-1690536487.1952565-22-102426177066420="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1690536487.1952565-22-102426177066420 `" ) && sleep 0'
Using module file /tmp/bwrap_1532067_kg3e3ujp/awx_1532067_hqbkbwry/requirements_collections/ansible_collections/ibm/power_hmc/plugins/modules/hmc_command.py
<jumphost_IP> PUT /var/lib/awx/.ansible/tmp/ansible-local-32q8itssp/tmpmm0v3krv TO /var/lib/awx/.ansible/tmp/ansible-tmp-1690536487.1952565-22-102426177066420/AnsiballZ_hmc_command.py
<jumphost_IP> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1690536487.1952565-22-102426177066420/ /var/lib/awx/.ansible/tmp/ansible-tmp-1690536487.1952565-22-102426177066420/AnsiballZ_hmc_command.py && sleep 0'
<jumphost_IP> EXEC /bin/sh -c '/usr/bin/python3 /var/lib/awx/.ansible/tmp/ansible-tmp-1690536487.1952565-22-102426177066420/AnsiballZ_hmc_command.py && sleep 0'
<jumphost_IP> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1690536487.1952565-22-102426177066420/ > /dev/null 2>&1 && sleep 0'

**"msg": "HmcError: b'ssh: connect to host <HMC_IP> port 22: Connection timed out'"**,
    "exception": "  File \"/tmp/ansible_ibm.power_hmc.hmc_command_payload_xrdct49e/ansible_ibm.power_hmc.hmc_command_payload.zip/ansible_collections/ibm/power_hmc/plugins/modules/hmc_command.py\", line 99, in run_hmc_adhoc_command\n  File \"/tmp/ansible_ibm.power_hmc.hmc_command_payload_xrdct49e/ansible_ibm.power_hmc.hmc_command_payload.zip/ansible_collections/ibm/power_hmc/plugins/module_utils/hmc_cli_client.py\", line 71, in execute\n    raise HmcError(errMsg)\n",
    "invocation": {
        "module_args": {
            "hmc_host": "<HMC_IP>",
            "hmc_auth": {
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "cmd": "uname -a"
        }
    },
    "_ansible_no_log": false,
    "changed": false,
    "_ansible_delegated_vars": {}

**Comment by naveenkandakur** [comment]
Are you able to do SSH to the HMC from your Ansible controller node?

**Comment by mshakeer03** [comment]
> Are you able to do SSH to the HMC from your Ansible controller node?

Thanks for the response, the Ansible controller cannot directly do an SSH to HMC, the connection path is, Ansible Controller (Ansible Tower)-->Proxy (VPN)-->Linux Jumphost--> Endpoint(HMC), as the infrastructure spans across different networks. The HMC commands using the ansible raw module do work in this environment though. Please let me know if you need more details.

**Comment by mshakeer03** [comment]
Is this a hard limitation given the connection path? and the pre-req, that the source of execution of these POWER HMC modules should be the ansible controller?

**Comment by naveenkandakur** [comment]
> Is this a hard limitation given the connection path? and the pre-req, that the source of execution of these POWER HMC modules should be the ansible controller?

Yes, Source of the Power HMC modules should be in the Ansible controller node

**Comment by AnilVijayan** [comment]
Closing this since there is no further discussion on this.
