### ISSUE TITLE
HMC_update_upgrade module _exit_ error during playbook execution.

### ISSUE THREAD

**Issue by jurajhajka** [IBM/ansible-power-hmc#77]
**HMC_update_upgrade module _exit_ error during playbook execution.**
We are getting error _exit_ in case module hmc_update_upgrade is used. During update or upgrade.

**To Reproduce**
simple playbook.

  - name: Update the HMC to the V9R2M952 build level from sftp location
    hmc_update_upgrade:
       hmc_host: '{{ inventory_hostname }}'
       hmc_auth: '{{ curr_hmc_auth }}'
       build_config: '{{ build_config }}'
          location_type: sftp
          hostname: xxxxxxx
          userid: root
          passwd: xxx
          build_file: /export/hmc/V910/vMH01857_x86.iso
       state: updated
    connection: local
    register: updated_hmc_build_info

2022-07-27 10:22:38,007 p=7995678 u=ansau n=ansible | <vhmc_ansible> EXEC /bin/sh -c 'sudo -H -S  -u root /bin/sh -c '"'"'echo
BECOME-SUCCESS-dqjezmhkbcpddkholxqnijtnmpyctcgh ; /usr/bin/python'"'"' && sleep 0'
2022-07-27 10:22:41,758 p=21954856 u=ansau n=ansible | fatal: [vhmc_ansible]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "build_config": {
                "build_file": "/export/hmc/V910/vMH01857_x86.iso",
                "hostname": "xxxxxxxx",
                "location_type": "sftp",
                "mount_location": null,
                "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "sshkey_file": null,
                "userid": "root"
            },
            "hmc_auth": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "hmc_host": "vhmc_ansible",
            "state": "updated"
        }
    },
    "msg": "AttributeError('__exit__',)"
}
2022-07-27 10:22:41,759 p=21954856 u=ansau n=ansible | ...ignoring

**Expected behavior**
Module should not exit with error after HMC is rebooting, should wait until HMC is up and continue witch checks .

**Environment (please complete the following information):**
 - HMC: tested with several versions of HMC code [V9R952, V9R1M910]
 - Python 3.7.12 
 - OpenSSH_8.1p1, OpenSSL 1.0.2u

**Comment by Alan-Fulton** [comment]
Following this issue closely.

**Comment by AnilVijayan** [comment]
The issue seems to be with python version. It looks like some how ansible engine picking lower version of pyhton (possibly 2.7)  which is not supported. You could as well try environment variable `ansible_python_interpreter` to enforce the python version as 3.7. Also you can confirm the python version used by the engine using the command `ansible --version`

**Comment by jurajhajka** [comment]
$ ansible --version
ansible 2.9.25
  config file = /home/ansau/project/ansible.cfg
  configured module search path = ['/home/ansau/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/freeware/lib/python3.7/site-packages/ansible
  executable location = /opt/freeware/bin/ansible
  python version = 3.7.12 (default, Dec 15 2021, 03:25:47) [GCC 8.3.0]

should be version 3.7

**Comment by AnilVijayan** [comment]
Can you please try once the execution with ansible_python_interpreter like below
`anisble-playbook -e ansible_python_interpreter=<python 3.7 path>`
Also please run with verbosity level `5` (-vvvvv) and share the standard out and another file that will get generated as `/tmp/ansible_power_hmc.log`

**Comment by jurajhajka** [comment]
I can confirm issue related to python 2.7.

module is using #!/usr/bin/python 
in our testing environment was pointing link to version 2.7. 
relink to version 3 resolved the issue.

**Comment by jurajhajka** [comment]
Thank you!

**Comment by AnilVijayan** [comment]
Improved the error message  regarding the non support of python 2.7
