### ISSUE TITLE
Shutdown parameter 

### ISSUE THREAD

**Issue by christophegehin** [IBM/ansible-power-hmc#91]
Hello

I'd like to know how to specify the type of shutdown I want to initiate :
- os shutdown
- os shutdown immediate
- immediate
- ...
I'm not able to find that parameter in the documentation.

Thanks you

**Comment by naveenkandakur** [comment]
Thanks for showing interest, Shutdown operation is supported with only immediate type, As of now user can't choose the different types of shutdown.

**Comment by christophegehin** [comment]
Thanks you for your answer.
Are you aware if there is any plan to add a parameter to choose shutdown type ?

Thanks you

**Comment by AnilVijayan** [comment]
Will add this into the pipeline for April release

**Comment by christophegehin** [comment]
Thanks you very much.

**Comment by naveenkandakur** [comment]
This is available as part of Apr-2023 release content hence marking as closed
